server:
  port: 8081
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://49.232.16.188:3306/qzmall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
#    url: jdbc:mysql://49.232.16.188:3306/qingzhu?useUnicode=true&characterEncoding=utf-8&useSSL=false

    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true

    platform: mysql
  security:
    user:
      name: docker
      password: 123456


mybatis:
  # 全局配置文件位置
#  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
#    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com:
      docker:
        qmmall:
          mapper: debug

# 七牛云存储
oss:
  qiniu:
    domain: http://hn-bkt-clouddn-com-idvcz9d.www.qiniudns.com # 访问域名(默认使用七牛云测试域名)
    accessKey: 3WhI6g6ds9vo0Gw6V87rsNJfvXKOdwM6GWxf8gl4 # 公钥
    secretKey: bKpVR3TrwOhkPWwyaEgsFwrDutzbeF4uH9oB0kpz # 私钥
    bucketName: qzmall  #存储空间名称

adminster:
  username: admin
  password: 123456